import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "../../app/globals.css";
// import 'react-toastify/dist/ReactToastify.css';
import { AppSidebar } from "@/components/admin-template/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PDAM App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar/>        
          {/* class biar full screen */}
          <main className="flex-1 w-full min-w-0"> 
            <SidebarTrigger/>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
